name: Continuous Integration

on:
  push:
    branches:
      - develop

jobs:

  #PROCESSO DE BUILD
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Build Gradle
        run: gradle build

  #PROCESSO DE LOGIN E PUSH DA IMAGEM NO DOCKERHUB
  dockerhub-push:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Dockerhub Log-in
        uses: : docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Dockerhub image push
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/consulta_cep_api:latest ${{ secrets.DOCKER_USERNAME }}/consulta_cep_api:${{github.run_id}}
          
          docker push ${{ secrets.DOCKER_USERNAME }}/consulta_cep_api:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/consulta_cep_api:latest